apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-mlops-app
  namespace: mlops
  labels:
    app:     iris-mlops-app
    project: mlops-project3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-mlops-app
  template:
    metadata:
      labels:
        app: iris-mlops-app
    spec:
      containers:
      - name: iris-api
        image: iris-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7000
        env:
        - name: MLFLOW_TRACKING_URI
          value: "http://192.168.49.1:5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 5
