apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-mlops-app
  namespace: mlops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iris-api
  template:
    metadata:
      labels:
        app: iris-api
    spec:
      containers:
      - name: iris-api
        image: syedaunalikazmi/iris-api:latest # Use your DockerHub username
        env:
        - name: MLFLOW_TRACKING_URI
          value: "https://dagshub.com/kazmiaun032/mlops-project3.mlflow"
        - name: MLFLOW_TRACKING_USERNAME
          value: "kazmiaun032"
        - name: MLFLOW_TRACKING_PASSWORD
          value: "c80eaea30585653770fe829c28e2382a6cb81651"
        ports:
        - containerPort: 7000
